<style>
    h2 {
        margin-top: 20px;
    }
</style>

<h1 style="color:#f1703d"> Mirasvit Basic Data Entering Example</h1>

<h2>Simple Spinner Widget</h2>

<input type="text" class="spintest">

<h2>Spinner with variable spinning speed</h2>

<input type="text" value="0" class="spintest2">

<h2>Spinner with cycled values spinning</h2>

<input type="text" value="1" class="spintest3">


<script>
    require([
            'jquery',
            'jquery/ui',
        ],
        function($, spinner) {
            $(".spintest").spinner();
        }
    );


    require([
            'jquery',
            'jquery/ui',
        ],
        function($, spinner) {
            $(".spintest2").spinner({
                max: 10000,
                min: 0,
                incremental: function (spins) {
                    if(spins > 10 && spins < 20) {
                        return 10;
                    }
                    if(spins >= 20) {
                        return 100;
                    }
                    return 1;
                }
            });
        }
    );

    require([
            'jquery',
            'jquery/ui',
        ],
        function($, spinner) {
            $(".spintest3").spinner({
                max: 10000,
                min: -1,
                spin: function (event, ui) {
                    if ( ui.value > 9999 ) {
                        $( this ).spinner( "value", 0);
                        return false;
                    } else if ( ui.value == -1 ) {
                        $( this ).spinner( "value", 10000);
                        return false;
                    }
                }
            });
        }
    );
</script>


