<h1 style="color:#f1703d"> Mirasvit Navigation Widget Example</h1>

<style>
    .ui-menu {
        width: 200px;
    }

    .ui-menu-item:hover {
        background-color: lightgrey;
    }

    label {
        display: block;
    }

    select {
        width: 200px;
    }

</style>

<br>

<h2>Simple List-based Menu</h2>

<ul id="listmenu">
    <li class="ui-menu-item">Calendar</li>
    <li class="ui-menu-item">Prompt</li>
    <li class="ui-menu-item">JQuery Extended Widgets
        <ul>
            <li class="ui-menu-item">Progressbar</li>
            <li class="ui-menu-item">Slider</li>
            <li class="ui-menu-item">Spinner</li>
            <li class="ui-menu-divider">-</li>
            <li class="ui-menu-item">Datepicker</li>
            <li class="ui-menu-item">Tooltip</li>
        </ul>
    </li>
    <li class="ui-menu-item">Confirmation</li>
    <li class="ui-menu-item">Quick Search</li>
</ul>

<br><br>

<h2>Dropdown Menu with Grouping</h2>

<label for="files">Select a file:</label>
<select name="files" id="files">
    <optgroup label="Scripts">
        <option value="jquery">jQuery.js</option>
        <option value="jqueryui">ui.jQuery.js</option>
    </optgroup>
    <optgroup label="Other files">
        <option value="somefile">Some unknown file</option>
        <option value="someotherfile">Some other file</option>
    </optgroup>
</select>

<script>
    require([
            'jquery',
            'jquery/ui'
        ],
        function($, menu) {
            $("#listmenu").menu();
        }
    );

    require([
            'jquery',
            'jquery/ui'
        ],
        function($, selectmenu) {
            $( "#files" ).selectmenu();
        }
    );
</script>